## Import Libraries

In [2]:
library(dplyr)
library(tidyverse)

## Filter

In [3]:
# print first 6 rows of mtcars
head(mtcars)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [4]:
# show number of rows and number of columns
dim(mtcars)

[1] 32 11

In [5]:
# Display those records of dataset who's mpg > 20
filter(mtcars, mpg > 20)

               mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [6]:
# Create a new column make_model
mtcars$make_model <- rownames(mtcars)

In [7]:
head(mtcars)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1
                  make_model
Mazda RX4         Mazda RX4
Mazda RX4 Wag     Mazda RX4 Wag
Datsun 710        Datsun 710
Hornet 4 Drive    Hornet 4 Drive
Hornet Sportabout Hornet Sportabout
Valiant           Valiant

In [9]:
subset <- filter(mtcars, mpg > 20)
filter(subset, qsec < 17)

              mpg  cyl disp  hp  drat wt    qsec  vs am gear carb make_model
Mazda RX4     21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4    Mazda RX4
Porsche 914-2 26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2    Porsche 914-2
Lotus Europa  30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2    Lotus Europa

In [10]:
filter(mtcars, mpg > 20,
       qsec < 17,
       gear >= 5)

              mpg  cyl disp  hp  drat wt    qsec vs am gear carb make_model
Porsche 914-2 26.0 4   120.3  91 4.43 2.140 16.7 0  1  5    2    Porsche 914-2
Lotus Europa  30.4 4    95.1 113 3.77 1.513 16.9 1  1  5    2    Lotus Europa

In [11]:
mtcars <- mtcars[, 1:11]

## Arrange

In [13]:
arrange(mtcars, qsec)

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2

In [14]:
arrange(mtcars, desc(qsec))

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4

In [15]:
arrange(mtcars, desc(cyl),
        desc(wt))

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2

## Filter and Arrange

In [17]:
df <- mtcars

In [18]:
df %>%
  filter(mpg > 20)

               mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [20]:
df %>%
  filter(mpg > 20, gear >= 4) %>%
  arrange(qsec)

               mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2

# Mutate to Change Column

In [21]:
df <- mtcars

In [22]:
df$new_wt <- 1000 * df$wt

In [23]:
head(df)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb new_wt
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4    2620
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4    2875
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1    2320
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1    3215
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2    3440
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1    3460

In [24]:
df$new_col <- df$cyl +
  df$wt +
  df$am +
  df$gear

In [25]:
head(df)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb new_wt
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4    2620
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4    2875
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1    2320
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1    3215
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2    3440
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1    3460
                  new_col
Mazda RX4         13.620
Mazda RX4 Wag     13.875
Datsun 710        11.320
Hornet 4 Drive    12.215
Hornet Sportabout 14.440
Valiant           12.460

In [27]:
df <- df %>%
  mutate(new_col = cyl + wt + am + gear)
head(df)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb new_wt
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4    2620
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4    2875
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1    2320
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1    3215
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2    3440
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1    3460
                  new_col
Mazda RX4         13.620
Mazda RX4 Wag     13.875
Datsun 710        11.320
Hornet 4 Drive    12.215
Hornet Sportabout 14.440
Valiant           12.460

In [28]:
df <- df %>%
  mutate(new_col = 1, new_wt = 1000 * wt)
head(df)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb new_wt
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4    2620
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4    2875
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1    2320
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1    3215
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2    3440
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1    3460
                  new_col
Mazda RX4         1
Mazda RX4 Wag     1
Datsun 710        1
Hornet 4 Drive    1
Hornet Sportabout 1
Valiant           1

In [29]:
df %>%
    mutate(decile = ntile(qsec, 10)) %>%
    head()

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb new_wt
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4    2620
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4    2875
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1    2320
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1    3215
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2    3440
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1    3460
                  new_col decile
Mazda RX4         1        2
Mazda RX4 Wag     1        3
Datsun 710        1        7
Hornet 4 Drive    1        8
Hornet Sportabout 1        3
Valiant           1       10

# Filter, Mutate, Arrange

In [30]:
df <- mtcars
head(df)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [31]:
df %>%
    mutate(decile = ntile(qsec, 10)) %>%
    filter(decile <= 3)

                  mpg  cyl disp  hp  drat wt    qsec  vs am gear carb decile
Mazda RX4         21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4    2
Mazda RX4 Wag     21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4    3
Hornet Sportabout 18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2    3
Duster 360        14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4    2
Dodge Challenger  15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2    2
Camaro Z28        13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4    1
Porsche 914-2     26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2    2
Lotus Europa      30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2    3
Ford Pantera L    15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4    1
Ferrari Dino      19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6    1
Maserati Bora     15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8    1

In [32]:
df %>%
    mutate(decile = ntile(qsec, 10), over_20_mpg = ifelse(mpg > 20, 1, 0)) %>%
    filter(decile <= 3, over_20_mpg == 1)

              mpg  cyl disp  hp  drat wt    qsec  vs am gear carb decile
Mazda RX4     21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4    2
Mazda RX4 Wag 21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4    3
Porsche 914-2 26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2    2
Lotus Europa  30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2    3
              over_20_mpg
Mazda RX4     1
Mazda RX4 Wag 1
Porsche 914-2 1
Lotus Europa  1

In [34]:
df %>%
    mutate(decile = ntile(qsec, 10), over_20_mpg = ifelse(mpg > 20, 1, 0)) %>%
    filter(decile <= 3, over_20_mpg == 1) %>%
    arrange(desc(wt))

              mpg  cyl disp  hp  drat wt    qsec  vs am gear carb decile
Mazda RX4 Wag 21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4    3
Mazda RX4     21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4    2
Porsche 914-2 26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2    2
Lotus Europa  30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2    3
              over_20_mpg
Mazda RX4 Wag 1
Mazda RX4     1
Porsche 914-2 1
Lotus Europa  1

In [36]:
df %>%
    mutate(decile = ntile(qsec, 10), over_20_mpg = ifelse(mpg > 20, 1, 0)) %>%
    filter(decile <= 3, over_20_mpg == 1) %>%
    arrange(desc(wt)) %>%
    select(mpg, wt, qsec, gear)

              mpg  wt    qsec  gear
Mazda RX4 Wag 21.0 2.875 17.02 4
Mazda RX4     21.0 2.620 16.46 4
Porsche 914-2 26.0 2.140 16.70 5
Lotus Europa  30.4 1.513 16.90 5