In [6]:
library(tidyverse)

# Summarise Single Variable

In [7]:
summary(mtcars$mpg)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  10.40   15.43   19.20   20.09   22.80   33.90

In [9]:
mtcars %>%
    summarise(mean_mpg = mean(mpg))
mtcars %>%
    summarize(mean_mpg = mean(mpg))

  mean_mpg
1 20.09062

  mean_mpg
1 20.09062

In [10]:
mtcars %>%
    summarise(count = n())

  count
1 32

# Summarise Multiple Variable

In [11]:
df <- mtcars

In [12]:
df %>%
    summarize(mean_wt = mean(wt), mean_hp = mean(hp))

  mean_wt mean_hp
1 3.21725 146.6875

In [13]:
mtcars %>%
    summarize(mean_wt = mean(wt), 
              mean_hp = mean(hp), 
              hp_per_wt = mean_hp / mean_wt)

  mean_wt mean_hp  hp_per_wt
1 3.21725 146.6875 45.59406

### summarize_all()

In [14]:
df %>%
    summarize_all(mean)

  mpg      cyl    disp     hp       drat     wt      qsec     vs     am
1 20.09062 6.1875 230.7219 146.6875 3.596563 3.21725 17.84875 0.4375 0.40625
  gear   carb
1 3.6875 2.8125

In [15]:
df %>%
    summarize_all(min)

  mpg  cyl disp hp drat wt    qsec vs am gear carb
1 10.4 4   71.1 52 2.76 1.513 14.5 0  0  3    1

### summarise_at()

In [16]:
df %>%
    summarise_at(vars(mpg), funs(mean, median))

Warning message:
"`funs()` was deprecated in dplyr 0.8.0.
Please use a list of either functions or lambdas:

  # Simple named list:
  list(mean = mean, median = median)

  # Auto named with `tibble::lst()`:
  tibble::lst(mean, median)

  # Using lambdas
  list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated."

  mean     median
1 20.09062 19.2

In [17]:
df <- as_tibble(df)
df %>%
    summarise_at(vars(mpg), funs(mean, median))

  mean     median
1 20.09062 19.2

In [18]:
df %>%
    summarise_at(vars(mpg), funs(mean, median, max))

  mean     median max
1 20.09062 19.2   33.9

In [19]:
df %>%
    summarise_at(vars(mpg, hp), funs(mean, median, max))

  mpg_mean hp_mean  mpg_median hp_median mpg_max hp_max
1 20.09062 146.6875 19.2       123       33.9    335

# group_by verb

In [20]:
df <- mtcars
head(df)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [21]:
df %>%
    group_by(cyl) %>%
    summarise(mean_hp = mean(hp))

  cyl mean_hp
1 4    82.63636
2 6   122.28571
3 8   209.21429

In [22]:
df %>%
    group_by(cyl) %>%
    summarise(mean_hp = mean(hp),
             mean_wt = mean(wt),
             hp_per_wt = mean_hp / mean_wt,
             count = n())

  cyl mean_hp   mean_wt  hp_per_wt count
1 4    82.63636 2.285727 36.15320  11
2 6   122.28571 3.117143 39.23006   7
3 8   209.21429 3.999214 52.31385  14

In [26]:
df %>%
    group_by(cyl, gear) %>%
    summarise(mean_hp = mean(hp),
             mean_wt = mean(wt))

`summarise()` has grouped output by 'cyl'. You can override using the `.groups`
argument.

  cyl gear mean_hp  mean_wt
1 4   3     97.0000 2.465000
2 4   4     76.0000 2.378125
3 4   5    102.0000 1.826500
4 6   3    107.5000 3.337500
5 6   4    116.5000 3.093750
6 6   5    175.0000 2.770000
7 8   3    194.1667 4.104083
8 8   5    299.5000 3.370000

In [27]:
df %>%
    group_by(cyl, gear) %>%
    summarise(mean_hp = mean(hp),
             mean_wt = mean(wt),
             count = n())

`summarise()` has grouped output by 'cyl'. You can override using the `.groups`
argument.

  cyl gear mean_hp  mean_wt  count
1 4   3     97.0000 2.465000  1
2 4   4     76.0000 2.378125  8
3 4   5    102.0000 1.826500  2
4 6   3    107.5000 3.337500  2
5 6   4    116.5000 3.093750  4
6 6   5    175.0000 2.770000  1
7 8   3    194.1667 4.104083 12
8 8   5    299.5000 3.370000  2

# ungroup()

In [28]:
df %>%
    group_by(cyl, gear) %>%
    summarise(mean_hp = mean(hp),
             mean_wt = mean(wt),
             count = n()) %>%
    ungroup()

`summarise()` has grouped output by 'cyl'. You can override using the `.groups`
argument.

  cyl gear mean_hp  mean_wt  count
1 4   3     97.0000 2.465000  1
2 4   4     76.0000 2.378125  8
3 4   5    102.0000 1.826500  2
4 6   3    107.5000 3.337500  2
5 6   4    116.5000 3.093750  4
6 6   5    175.0000 2.770000  1
7 8   3    194.1667 4.104083 12
8 8   5    299.5000 3.370000  2