### Gather

Make a 'wide' dataset 'long'

### Spread

Make a 'long' dataset 'wide'

### Separate and Extract

# Gather

In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
ldeaths

     Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
1974 3035 2552 2704 2554 2014 1655 1721 1524 1596 2074 2199 2512
1975 2933 2889 2938 2497 1870 1726 1607 1545 1396 1787 2076 2837
1976 2787 3891 3179 2011 1636 1580 1489 1300 1356 1653 2013 2823
1977 3102 2294 2385 2444 1748 1554 1498 1361 1346 1564 1640 2293
1978 2815 3137 2679 1969 1870 1633 1529 1366 1357 1570 1535 2491
1979 3084 2605 2573 2143 1693 1504 1461 1354 1333 1492 1781 1915

In [3]:
df <- data.frame(ldeaths)
head(df)

  ldeaths
1 3035
2 2552
3 2704
4 2554
5 2014
6 1655

In [4]:
messy <- data.frame(name = c("hamed", "moon", "raza", "danish", "basit"),
                   a = c(99,98,78,68,96),
                   b = c(91,90,94,89,77))
messy

  name   a  b
1 hamed  99 91
2 moon   98 90
3 raza   78 94
4 danish 68 89
5 basit  96 77

In [5]:
messy %>%
    gather(drug, volume, a:b)

   name   drug volume
1  hamed  a    99
2  moon   a    98
3  raza   a    78
4  danish a    68
5  basit  a    96
6  hamed  b    91
7  moon   b    90
8  raza   b    94
9  danish b    89
10 basit  b    77

In [6]:
messy <- data.frame(name = c("hamed", "moon", "raza", "danish", "basit"),
                   a = c(99,98,78,68,96),
                   b = c(91,90,94,89,77),
                   c = c(91,90,94,89,77))
messy
messy %>%
    gather(drug, volume, a:c)

  name   a  b  c
1 hamed  99 91 91
2 moon   98 90 90
3 raza   78 94 94
4 danish 68 89 89
5 basit  96 77 77

   name   drug volume
1  hamed  a    99
2  moon   a    98
3  raza   a    78
4  danish a    68
5  basit  a    96
6  hamed  b    91
7  moon   b    90
8  raza   b    94
9  danish b    89
10 basit  b    77
11 hamed  c    91
12 moon   c    90
13 raza   c    94
14 danish c    89
15 basit  c    77

# Spread

In [7]:
messy
long_df <- messy %>%
    gather(drug, volume, a:c)
long_df

  name   a  b  c
1 hamed  99 91 91
2 moon   98 90 90
3 raza   78 94 94
4 danish 68 89 89
5 basit  96 77 77

   name   drug volume
1  hamed  a    99
2  moon   a    98
3  raza   a    78
4  danish a    68
5  basit  a    96
6  hamed  b    91
7  moon   b    90
8  raza   b    94
9  danish b    89
10 basit  b    77
11 hamed  c    91
12 moon   c    90
13 raza   c    94
14 danish c    89
15 basit  c    77

In [8]:
long_df %>%
    spread(key = drug, value = volume)

  name   a  b  c
1 basit  96 77 77
2 danish 68 89 89
3 hamed  99 91 91
4 moon   98 90 90
5 raza   78 94 94

In [9]:
long_df %>%
    spread(drug, volume)

  name   a  b  c
1 basit  96 77 77
2 danish 68 89 89
3 hamed  99 91 91
4 moon   98 90 90
5 raza   78 94 94

In [10]:
long_df
length(long_df$name)
long_df <- long_df[-c(1, 6), ]
long_df
length(long_df$name)

   name   drug volume
1  hamed  a    99
2  moon   a    98
3  raza   a    78
4  danish a    68
5  basit  a    96
6  hamed  b    91
7  moon   b    90
8  raza   b    94
9  danish b    89
10 basit  b    77
11 hamed  c    91
12 moon   c    90
13 raza   c    94
14 danish c    89
15 basit  c    77

[1] 15

   name   drug volume
2  moon   a    98
3  raza   a    78
4  danish a    68
5  basit  a    96
7  moon   b    90
8  raza   b    94
9  danish b    89
10 basit  b    77
11 hamed  c    91
12 moon   c    90
13 raza   c    94
14 danish c    89
15 basit  c    77

[1] 13

In [11]:
long_df %>%
spread(drug, volume)

  name   a  b  c
1 basit  96 77 77
2 danish 68 89 89
3 hamed  NA NA 91
4 moon   98 90 90
5 raza   78 94 94

In [12]:
long_df %>%
spread(drug, volume, fill = 0)

  name   a  b  c
1 basit  96 77 77
2 danish 68 89 89
3 hamed   0  0 91
4 moon   98 90 90
5 raza   78 94 94

# Separate and Extract
### Separate
Takes string values in a single column and splits into multiple columns
### Extract
Removes value from string column that matches specified conditions

In [17]:
messy <- data.frame(name = c("hamed raza", "moon lahori", "raza raza", "danish kaimka", "basit kashmari"),
                   a = c(99,98,78,68,96),
                   b = c(91,90,94,89,77),
                   c = c(91,90,94,89,77))
messy

  name           a  b  c
1 hamed raza     99 91 91
2 moon lahori    98 90 90
3 raza raza      78 94 94
4 danish kaimka  68 89 89
5 basit kashmari 96 77 77

In [18]:
messy %>%
separate(name, into = c("first_name", "last_name"), sep = " ")

  first_name last_name a  b  c
1 hamed      raza      99 91 91
2 moon       lahori    98 90 90
3 raza       raza      78 94 94
4 danish     kaimka    68 89 89
5 basit      kashmari  96 77 77

In [19]:
messy %>%
separate(name, into = c("first_name", "last_name"))

  first_name last_name a  b  c
1 hamed      raza      99 91 91
2 moon       lahori    98 90 90
3 raza       raza      78 94 94
4 danish     kaimka    68 89 89
5 basit      kashmari  96 77 77

In [20]:
messy %>%
separate(name, into = c("first_name", "last_name"))

  first_name last_name a  b  c
1 hamed      raza      99 91 91
2 moon       lahori    98 90 90
3 raza       raza      78 94 94
4 danish     kaimka    68 89 89
5 basit      kashmari  96 77 77

In [22]:
messy %>%
    extract(name, "raza", regex = "(raza)")

  raza a  b  c
1 raza 99 91 91
2 NA   98 90 90
3 raza 78 94 94
4 NA   68 89 89
5 NA   96 77 77

In [23]:
messy %>%
    extract(name, "raza", regex = "(raza)", remove = FALSE)

  name           raza a  b  c
1 hamed raza     raza 99 91 91
2 moon lahori    NA   98 90 90
3 raza raza      raza 78 94 94
4 danish kaimka  NA   68 89 89
5 basit kashmari NA   96 77 77